server:
  port: ${PORT}

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: authuser
            uri: lb://ead-authuser
            predicates:
              - Path=/ead-authuser/**
          - id: course-service
            uri: lb://EAD-COURSE-SERVICE
            predicates:
              - Path=/ead-course/**
          - id: notification-service
            uri: lb://EAD-NOTIFICATION-SERVICE
            predicates:
              - Path=/ead-notification/**
