server:
  port: 8084
  servlet:
    context-path: '/ead-notification-hex'

spring:
  application:
    name: ead-notification-service-hex
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-notification-hex
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true

  rabbitmq:
    addresses: amqps://xozkkvzu:inlgUeJBLDp7OYDeEazO-_xxtKhdIdqg@beaver.rmq.cloudamqp.com/xozkkvzu

ead:
  broker:
    exchange:
      notificationCommandExchange: ead.notificationcommand
    queue:
      notificationCommandQueue:
        name: ead.notificationcommand.ms.notification
    key:
      notificationCommandKey: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
